-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 09:42:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospitalV1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospitalV1` ;

-- -----------------------------------------------------
-- Schema hospitalV1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospitalV1` DEFAULT CHARACTER SET utf8 ;
USE `hospitalV1` ;

-- -----------------------------------------------------
-- Table `hospitalV1`.`DatosPersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`DatosPersonales` (
  `idDatosPersonales` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idDatosPersonales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Habitacion` (
  `idHabitacion` INT NOT NULL AUTO_INCREMENT,
  `nombreHabitacion` VARCHAR(45) NOT NULL,
  `disponible` VARCHAR(2) NOT NULL DEFAULT 'SI',
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`EstadoPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`EstadoPaciente` (
  `idEstadoPaciente` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadoPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `maxVisitas` INT(4) NOT NULL,
  `edadMin` INT(8) NOT NULL DEFAULT 0,
  `edadMax` INT(8) NOT NULL DEFAULT 150,
  `horarioInicio` TIME NOT NULL DEFAULT '00:00',
  `horarioFin` TIME NOT NULL DEFAULT '23:59',
  `idDatosPersonales` INT NOT NULL,
  `idEstadoPaciente` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Paciente_DatosPersonales_idx` (`idDatosPersonales` ASC),
  INDEX `fk_Paciente_EstadoPaciente1_idx` (`idEstadoPaciente` ASC),
  CONSTRAINT `fk_Paciente_DatosPersonales`
    FOREIGN KEY (`idDatosPersonales`)
    REFERENCES `hospitalV1`.`DatosPersonales` (`idDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_EstadoPaciente`
    FOREIGN KEY (`idEstadoPaciente`)
    REFERENCES `hospitalV1`.`EstadoPaciente` (`idEstadoPaciente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Estancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Estancia` (
	`idPaciente` INT NOT NULL,
    `idHabitacion` INT NOT NULL,
  INDEX `fk_Estancia_Paciente1_idx` (`idPaciente` ASC),
  INDEX `fk_Estancia_Habitacion1_idx` (`idHabitacion` ASC),
  CONSTRAINT `fk_Estancia_Paciente`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospitalV1`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estancia_Habitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `hospitalV1`.`Habitacion` (`idHabitacion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`CodigoRFID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`CodigoRFID` (
  `idCodigoRFID` INT NOT NULL AUTO_INCREMENT,
  `codigoRFID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCodigoRFID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `horarioInicio` TIME NOT NULL DEFAULT '00:00',
  `horarioFin` TIME NOT NULL DEFAULT '23:59',
  `idDatosPersonales` INT NOT NULL,
  `idCodigoRFID` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_Medico_DatosPersonales1_idx` (`idDatosPersonales` ASC),
  INDEX `fk_Medico_CodigoRFID1_idx` (`idCodigoRFID` ASC),
  CONSTRAINT `fk_Medico_DatosPersonales1`
    FOREIGN KEY (`idDatosPersonales`)
    REFERENCES `hospitalV1`.`DatosPersonales` (`idDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_CodigoRFID1`
    FOREIGN KEY (`idCodigoRFID`)
    REFERENCES `hospitalV1`.`CodigoRFID` (`idCodigoRFID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Visitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Visitante` (
  `idVisitante` INT NOT NULL AUTO_INCREMENT,
  `idDatosPersonales` INT NOT NULL,
  `idCodigoRFID` INT NOT NULL,
  PRIMARY KEY (`idVisitante`),
  INDEX `fk_Visitante_DatosPersonales1_idx` (`idDatosPersonales` ASC),
  INDEX `fk_Visitante_CodigoRFID1_idx` (`idCodigoRFID` ASC),
  CONSTRAINT `fk_Visitante_DatosPersonales1`
    FOREIGN KEY (`idDatosPersonales`)
    REFERENCES `hospitalV1`.`DatosPersonales` (`idDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitante_CodigoRFID1`
    FOREIGN KEY (`idCodigoRFID`)
    REFERENCES `hospitalV1`.`CodigoRFID` (`idCodigoRFID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Visita` (
  `idVisita` INT NOT NULL AUTO_INCREMENT,
  `entrada` DATETIME(6) NOT NULL,
  `salida` DATETIME(6) NOT NULL,
  `idHabitacion` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `idCodigoRFID` INT NOT NULL,
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Habitacion1_idx` (`idHabitacion` ASC),
  INDEX `fk_Visita_Paciente1_idx` (`idPaciente` ASC),
  INDEX `fk_Visita_CodigoRFID1_idx` (`idCodigoRFID` ASC),
  CONSTRAINT `fk_Visita_Habitacion1`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `hospitalV1`.`Habitacion` (`idHabitacion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospitalV1`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_CodigoRFID1`
    FOREIGN KEY (`idCodigoRFID`)
    REFERENCES `hospitalV1`.`CodigoRFID` (`idCodigoRFID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- ----------------admin-------------------------------------
-- Table `hospitalV1`.`Enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Enfermero` (
  `idEnfermero` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `horarioInicio` TIME NOT NULL DEFAULT '00:00',
  `horarioFin` TIME NOT NULL DEFAULT '23:59',
  `idDatosPersonales` INT NOT NULL,
  `idCodigoRFID` INT NOT NULL,
  PRIMARY KEY (`idEnfermero`),
  INDEX `fk_Enfermero_DatosPersonales1_idx` (`idDatosPersonales` ASC),
  INDEX `fk_Enfermero_CodigoRFID1_idx` (`idCodigoRFID` ASC),
  CONSTRAINT `fk_Enfermero_DatosPersonales1`
    FOREIGN KEY (`idDatosPersonales`)
    REFERENCES `hospitalV1`.`DatosPersonales` (`idDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermero_CodigoRFID1`
    FOREIGN KEY (`idCodigoRFID`)
    REFERENCES `hospitalV1`.`CodigoRFID` (`idCodigoRFID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitalV1`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitalV1`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nombreAdmin` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
